//** View event.
export const GameViewEvent = {
  START_BUTTON_CLICKED: "START_BUTTON_CLICKED",
  AGAIN_BUTTON_CLICKED: "AGAIN_BUTTON_CLICKED",
  GAME_TIME_FINISHED: "GAME_TIME_FINISHED",
  CHANGE_PIECE_POS: "CHANGE_PIECE_POS",
};
