export const EventType = {
  START_GAME: "START_GAME",
  //INIT_GAME: "INIT_GAME",
  LOSE_GAME: "LOSE_GAME",
  WIN_GAME: "WIN_GAME",
  //CREATE_MODAL_WINDOW: "CREATE_MODAL_WINDOW",
  //HIDE_MODAL_WINDOW: "HIDE_MODAL_WINDOW",
  CHANGE_GAME_STATE: "CHANGE_GAME_STATE",
  GRID_UPDATED: "GRID_UPDATED",
  CLEAR_GRID: "CLEAR_GRID",
};
