export const GameEvents = {
  START_BUTTON_CLICKED: "START_BUTTON_CLICKED",
  AGAIN_BUTTON_CLICKED: "AGAIN_BUTTON_CLICKED",
  CHANGE_GAME_STATE: "CHANGE_GAME_STATE",
  WIN_GAME: "WIN_GAME",
  DRAG_END: "DRAG_END",
};
