export const GameEvents = {
  CHANGE_GAME_STATE: "CHANGE_GAME_STATE",
  WIN_GAME: "WIN_GAME",
  START_BUTTON_CLICKED: "START_BUTTON_CLICKED",
  AGAIN_BUTTON_CLICKED: "AGAIN_BUTTON_CLICKED",
  //GAME_TIME_FINISHED: "GAME_TIME_FINISHED",
  DRAG_END: "DRAG_END",
};
