export const GameEvents = {
  START_BUTTON_CLICKED: "START_BUTTON_CLICKED",
  AGAIN_BUTTON_CLICKED: "AGAIN_BUTTON_CLICKED",
  CHANGE_GAME_STATE: "CHANGE_GAME_STATE",
  SCORE_UPDATED: "SCORE_UPDATED",
  DRAG_END: "DRAG_END",
  FRUITS_MERGED: "FRUITS_MERGED",
};
